baseUrl= 'https://alphacjmav.github.io/multiopciones/'
languageCode = 'es'
title = 'MultiOpciones'
theme = "simple-snipcart-shop"
contentDir = "content/products"
publishDir = "docs"
[taxonomies]
  marca = "marcas"

[params]
  instagram = "multiopciones"
  header = "Multiopciones"
  description = "Las Mejores Marcas Líderes"
  products_title = "Nuestros Productos"
  reviews_title = "Por qué Multiopciones ®"
  not_found = "No hay productos de esa categoría."
  
  categories = [
    "Fragancias",
    "el",
    "ella"
  ]

  marca = [
  "Avon",
  "Natura",
  "Violeta",
  "Bagues",
  "Ofertas",
  ]

    collage = [
    "/multiopciones/images/collage1/1.jpg",
    "/multiopciones/images/collage1/2.jpg",
    "/multiopciones/images/collage1/3.png",
    "/multiopciones/images/collage1/4.jpg",
    "/multiopciones/images/collage1/5.jpg",
    "/multiopciones/images/collage1/6.jpg",
    "/multiopciones/images/collage1/7.jpg",
    "/multiopciones/images/collage1/8.jpg"
  ]

[author]
name = "Alpha Maverick"

  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  snipcart_key = ""
  favicon= "/images/favicon.png"